sudo: false

language: node_js
node_js:
  - node

addons:
  apt:
    packages:
      - libxml2-utils

before_script:
  - xmllint --version
  - npx eclint --version
  - npx svg2png --version
script:
  - make travis
